Fix absolute path in the example
The code without this fix will result in an error:

```
repl:1:> (import /build/mymod :as mymod)
error: could not find module /build/mymod:
    /usr/local/lib/janet/build/mymod.jimage
    /usr/local/lib/janet/build/mymod.janet
    /usr/local/lib/janet/build/mymod/init.janet
    /usr/local/lib/janet/build/mymod.so
    /build/mymod.jimage
    /build/mymod.janet
    /build/mymod/init.janet
    /build/mymod.so
  in require-1 [boot.janet] on line 2774, column 20
  in import* [boot.janet] on line 2813, column 15
  in _thunk [repl] (tailcall) on line 1, column 1
```

Not a big deal for an experienced Linux user I guess. Never the
less, we all do copy paste and expect things to just work :-).